### ISSUE TITLE
YOUR .ENV KEY IS VISIBLE!!!

### ISSUE THREAD

**Issue by rayhanadev** [alfnielsen/languagemaker#1]
Please use Github and hide your .env variables! We can see them and access your Firebase project.

**Comment by darkdarcool** [comment]
OMG i just noticed that! Name is something else so it is secret!!!!

**Comment by rayhanadev** [comment]
@darkdarcool no it's better to [use Github itself to hide it](https://docs.github.com/en/actions/reference/environment-variables).

**Comment by darkdarcool** [comment]
oh ok

**Comment by alfnielsen** [comment]
Thanks for the warning 
The firebase account was just a test account for trying it as proof of concept.
Sense I don't have time for this project at the moment, I have removed the actual firebase app,
if there should be some real security problem.

Beside that, I haven't used a lot of time reading into the security of firebase,
but the APP_ID and APP_Key most be exposed in the JS before any user are logged in,
so both are public (when the code is deployed)
https://firebase.google.com/docs/projects/api-keys

Thereby not said its a good idea to have them here in a publish repository :)
But I needed a fast test and I couldn't find a fast solution for this 
(original it was just in the code directly!)

I don't see how to have a JS app with this information without exposing the keys - and solutions like "Send it from your back end" don't make sense, since this tries to be serverless 
(we don't want to have a backend, we just want firebase, aka firebase are the backend)

**Comment by rayhanadev** [comment]
Ah, completely understood. I just wanted to make you aware of it was all :)
